# Using an official Node image compatible with v22
FROM node:22.7.0

# Set the working directory
WORKDIR /app

# Copy the package.json and install dependencies
COPY package*.json ./
RUN npm install
# RUN npm install -g vite

# Copy the rest of the application files
COPY . .

# Build the Vite.js application
RUN npm run build

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["npm", "run", "dev"]
