# Using Node.js version 20
FROM node:20.17.0

# Set the working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install
# RUN npm install -g strapi

# Copy the Strapi app files
COPY . .

# Expose the Strapi port
EXPOSE 1337

# Start Strapi
CMD ["npm", "run", "develop"]
